### ISSUE TITLE
Add support for icons on the Right Hand Side

### ISSUE THREAD

**Issue by JohnnyMorganz** [1ForeverHD/HDAdmin#12]
It would be useful if there were the ability to add Icons on the right hand side of the Topbar (Next to the ... button)

**Comment by Lucke0051** [comment]
Indeed +1

**Comment by 1ForeverHD** [comment]
My first thoughts is to introduce two methods: ``icon:setRight()`` and ``icon:setLeft()``. When an icon is set-right, it snaps next to the inv/back/emotes toggle (or to its position if that toggle is disabled), and once again the icons with the highest order display furthest right.

**Comment by JohnnyMorganz** [comment]
I assumed that the Left buttons and the Right Buttons would have seperate display orders, as it would be easier to add buttons to either the left or the right, as they shouldn't necessarily be linked.

With this, the lowest Display Order would be closest to the toggle, and higher display orders push further into the the middle (kind of like right-to-left writing).

**Comment by 1ForeverHD** [comment]
Left and right icon display orders will be independent of each other.

Good call, on second consideration it makes sense to have lowest furthest right (for right-icons) so that sides can be flipped with ease.
