### ISSUE TITLE
Add support for Icon ToolTips

### ISSUE THREAD

**Issue by JohnnyMorganz** [1ForeverHD/HDAdmin#13]
Having inbuilt support to create tool tips for Icons would be useful for new users looking at the icons who may not completely understand what they do.

These tooltips would support the theme implemented for that icon.

I am unsure if this is something the `setHoverFunction` is expected to cover, however this would make it easier to create tool tips, especially those which match the themes implemented

**Comment by 1ForeverHD** [comment]
Something like this? 

![image](https://user-images.githubusercontent.com/51117782/84897594-c1713f80-b09d-11ea-9136-2df834eb7140.png)

If so, I'll most likely introduce a method called ``:setTip(stringOfYourToolTip)`` which adds the tip, and calling ``setTip(nil)`` removed it.

**Comment by Lucke0051** [comment]
Right click would also be cool, like if you right clicked a button you could have options that do different stuff. Would be really useful!
