### ISSUE TITLE
Right-click

### ISSUE THREAD

**Issue by Lucke0051** [1ForeverHD/HDAdmin#14]
Right click would be pretty good, like if you right clicked a button you could have options that do different stuff. Would be really useful!

(Topbar+)

Edit: PR: https://github.com/1ForeverHD/HDAdmin/pull/21

**Comment by 1ForeverHD** [comment]
Can you provide examples of what you might do with this?

**Comment by Lucke0051** [comment]
Maybe you have a shop or something like a menu, then instead of opening it and then pressing trade or something, you could just right-click and click trade really quickly!  I am sure there are many other use-cases too. And if you use the button to like cycle between maybe 4 options. You could right-click and select option right away.

**Comment by 1ForeverHD** [comment]
I can see that being useful for V3 (right click to quickly navigate to pages like Commands for example). Alrighty, I'll add this to Topbar+ however it's not something I'll be able to complete until after V3 is complete, so some months down the road.

**Comment by Lucke0051** [comment]
Awesome!
