### ISSUE TITLE
Console support for Topbar+

### ISSUE THREAD

**Issue by Exo-Byte** [1ForeverHD/HDAdmin#19]
I was playing a game that had HD Admin in it on an Xbox One console, when I noticed that ROBLOX's rounded UI icons on the new top-bar are not present, yet the HD Admin logo is. (Again, I'm not sure exactly how detecting a player's platform would be possible, as ROBLOX only provides input-type detection APIs.)

**Comment by Lucke0051** [comment]
Do you have any images?

**Comment by 1ForeverHD** [comment]
Good call!
![image](https://user-images.githubusercontent.com/51117782/86134712-dc05d880-bae1-11ea-8239-ed9738650cda.png)

To do:
- [ ] Account for the offset of the missing menu icon
- [ ] Disable the fake chat if called and player is using a console

**Comment by 1ForeverHD** [comment]
For console...
1. Increase the size of icons by 100-200%
2. If a fakechat icon is created, disable/block it
3. Shift all icons to fill this void (left by no roblox and chat icon)
4. Hide topbar+, and have it toggled using inputs such as down on the DPad (to open) then B to close
5. Setup UI to indicate these actions (e.g. have a down-DPad icon in top left corner, and B icon when opened)
6. 'Pause' gameplay controls when opened

Here's a great example from Car Crushers 2:
https://discordapp.com/channels/528179091548012544/582621372048474150/728245377131741184
