### ISSUE TITLE
HD Admin menu too large in portrait mode

### ISSUE THREAD

**Issue by Lucke0051** [1ForeverHD/HDAdmin#22]
When in portrait mode the HD Admin mode is way to large. ![image](https://user-images.githubusercontent.com/30857678/86165615-d88b4500-bb13-11ea-9ea1-684bb01215ca.png)
Maybe this can wait until V3, there isn’t really that many games that use portrait mode and it’s still useable. Just wanted to left you know so V3 works on all screens.

**Comment by 1ForeverHD** [comment]
Thanks, I wasn't aware of this, I'll keep that in mind for the V3 client! Feel free to open up this issue again if the bug persist for V3
