### ISSUE TITLE
Notification font isn't matching the new Roblox UI

### ISSUE THREAD

**Issue by Lucke0051** [1ForeverHD/HDAdmin#23]
A small issue, just change the font to Gotham Bold or some other Gotham font
![notification](https://user-images.githubusercontent.com/30857678/86218284-dad7b880-bb80-11ea-8c2e-0fe708dfb4cc.png)

**Comment by 1ForeverHD** [comment]
The default Roblox notification font isn't actually Gotham Bold, unlike some other default CoreGuis. If the font changes in the future to be more consistent, I'll also change Topbar+ to follow.
