### ISSUE TITLE
Ability to disable the API

### ISSUE THREAD

**Issue by MrSaturnss** [1ForeverHD/HDAdmin#43]
I would like to request the ability to disable the API in HD Admin. Having the API enabled could be potentially dangerous if an unauthorised person has access to the server-side through a backdoor or other methods and they can then rank themselves to admin without the creator's knowledge.

**Comment by 1ForeverHD** [comment]
This is like chucking water on an oil fire; it merely spreads the problem, makes your situation more complicated and the house still burns down.

Attempting to restrict services (such as destroying them, obfuscation, etc) to external users will only make our development more challenging and time consuming. There will always be ways to reference the codebase, and if they struggle with this users can simply upload and require their own copy with all the necessary admin permissions.
