### ISSUE TITLE
Zone+ V2

### ISSUE THREAD

**Issue by 1ForeverHD** [1ForeverHD/HDAdmin#61]
## Improvements
- [ ] move to new standalone repository with installer methods like topbar+ (plugin, rojo, etc)
- [ ] remove all require() dependencies
- [x] consider removing additonalHeight param as this causes confusion
- [ ] replace irrelevant : within non object methods to .
- [ ] improve tutorials to make people aware of using Zone.new() (in addition to createZone)
- [ ] add Destroy upper case alias
- [ ] consider making work with non-players

## Bugs
- [ ] have the raycast fire from the hrp centre (instead of feet) for improved accuracy on upwards slanting shapes dipping into the ground
![image](https://user-images.githubusercontent.com/51117782/97171989-4116c580-1786-11eb-9e91-6907531c42d3.png)

- [ ] explore rotated wedge bug. this may be solved by the points above
![image](https://user-images.githubusercontent.com/51117782/97173380-5f7dc080-1788-11eb-8be1-5129dee6378d.png)

- [ ] random generation appears to fail below other parts
Repo file: https://devforum.roblox.com/uploads/short-url/pn1v2zXgk3e5QxwU62m2QjnocD4.rbxl
![image](https://user-images.githubusercontent.com/51117782/97173489-90f68c00-1788-11eb-81ec-93cf6fd71a1c.png)

- [ ] cluster infinite recursion https://devforum.roblox.com/t/zone-errors/864654/5

## Main
- [ ] have a Zone module then a ZoneController as a child 
- [ ] for zone, support both players and parts
- [ ] have methods like :getPlayers, :getLocalPlayer, :getParts, :checkPlayerInZone, :checkLocalPlayerInZone, :checkPartInZone
- [ ] have events which automatically initiate a loop when connected to - .playerEntered, playerExited, partEntered, partExited, localPlayerEntered, localPlayerExited
- [ ] for players, dynamically change between region3 + raycasting and solely raycasting depending upon factors such as total volume across all zones, number of players in server, localPlayer loop, etc
- [ ] for parts, call region3 like normal then raycast, however if a part is anchored (or not) consider caching results based on enum.accuracy
- [ ] handle logic, decision making and even raycasting within the controller
- [ ] when raycasting, perform a centre check initially, then if this fails use angle math to get the face nearest to the closest zone centre, and perform an additional tiny raycast in that direction
- [ ] introduce enum.Accuracy with items such as 'Precise', 'High', 'Medium', 'Low' and a zone.accuracy property
- [ ] once again have :update and. updated for calculating the zones min and max bounds and region, but completely scrap the 'cluster system'
- [ ] introduce :getRandomPoint again but this time do purely a while loop with completely random casting
- [ ] for ZoneController, remove create/remove methods entirely and just have ZoneController.getZones()
- [ ] parent utility modules like Signal and Maid *under* the Zone module

**Comment by Alidonis** [comment]
what is zone+?

**Comment by 1ForeverHD** [comment]
See https://github.com/1ForeverHD/ZonePlus

It was originally developed within Nanoblox for Nnaoblox  but now it's a stand alone project.
