### ISSUE TITLE
A Question because of the HD Admin Script (MainModule v2)

### ISSUE THREAD

**Issue by Mikerrushhd1** [1ForeverHD/HDAdmin#63]
Yooooooo @1ForeverHD 

I am now looking and searching for a long Time for something so I want to do that if ur Admin you only can use commands at 1 Person, How can I do that? Where are the Settings that allows me to change that? So Admins only can use like Mods commands at only 1 Person (so they are not able to do ;(command) all anymore? Would be nice to know!

**Comment by 1ForeverHD** [comment]
Hi Mike, you'll be able to do this once Nanoblox is out with the new role settings:
https://github.com/1ForeverHD/HDAdmin/blob/development/Core/MainModule/Server/Services/RoleService.lua
![image](https://user-images.githubusercontent.com/51117782/103448155-5a0f8b80-4c8d-11eb-82dc-bcfaca665341.png)
