### ISSUE TITLE
Issue with the ;face command from HD Admin V2

### ISSUE THREAD

**Issue by SkeletonLordRL** [1ForeverHD/HDAdmin#64]
Hello! Is there any reason why the ;face command does not let you use roblox decals anymore? And if it does, it only seems to work for the owner of the game.

**Comment by 1ForeverHD** [comment]
Hey lord, we're developing an entirely new character system for Nanoblox so that should will likely fixed then. Feel free to open up another issue if it hasn't once Nanoblox is out
