### ISSUE TITLE
custom commands don't work

### ISSUE THREAD

**Issue by DarthNihilus1** [1ForeverHD/HDAdmin#67]
I've been trying to get them to work and they just won't. They used to work but I believe some update broke them or something.

**Comment by 1ForeverHD** [comment]
Custom commands appear to be working fine with the latest loader, can you provide more details?

![image](https://user-images.githubusercontent.com/51117782/104966959-0f567900-59da-11eb-9f2e-fe79fdb8d1e4.png)

![image](https://user-images.githubusercontent.com/51117782/104966907-f51c9b00-59d9-11eb-9cb6-53ec9cd54ca8.png)

**Comment by DarthNihilus1** [comment]
How do I get the latest loader ? I inserted the latest model of hd admin and still have issues . It says invalid command when trying to use

**Comment by DarthNihilus1** [comment]
this is an example of one of my commands:
`	{
		Name = "setwave";
		Aliases	= {'waveset'};
		Prefixes = {settings.Prefix};
		Rank = 3;
		RankLock = false;
		Loopable = false;
		Tags = {'debug','abusive'};
		Description = "Used to set the wave value to a number";
		Contributors = {};
		--
		Args = {'Number'};
		Function = function(speaker, args)
			game.Workspace.Wave.Value = tonumber(args[1])

		end;
		--
	};`

**Comment by 1ForeverHD** [comment]
This appears to work fine:
![image](https://user-images.githubusercontent.com/51117782/104967437-411c0f80-59db-11eb-9da9-1a48f413b9bc.png)

Are you command tables structured correctly?

Here's what I'm doing?

```lua
-- << RETRIEVE FRAMEWORK >>
local main = _G.HDAdminMain
local settings = main.settings



-- << COMMANDS >>
local module = {
	
	-----------------------------------
	{
	Name = "setwave";
	Aliases	= {'waveset'};
	Prefixes = {settings.Prefix};
	Rank = 3;
	RankLock = false;
	Loopable = false;
	Tags = {'debug','abusive'};
	Description = "Used to set the wave value to a number";
	Contributors = {};
	--
	Args = {'Number'};
	Function = function(speaker, args)
		game.Workspace.Wave.Value = tonumber(args[1])

	end;
	--
	};
	
	
	
	
	-----------------------------------
	
};



return module
```

**Comment by DarthNihilus1** [comment]
yeah thats basically how my script looks except I have more commands than that but I don't want to leak my game stuff xD

**Comment by DarthNihilus1** [comment]
Ok heres something interesting when i hit play the HD Admin is rename to hdadminworkspacefolder right? well that's empty

**Comment by 1ForeverHD** [comment]
If you need help writing custom commands feel free to hop on over to #hd-admin in our community: https://hd.community

I'll close this issue for the time being as we're currently using this github for only major core bugs in v2.
