### ISSUE TITLE
Random generation fails below other parts

### ISSUE THREAD

**Issue by 1ForeverHD** [1ForeverHD/HDAdmin#9]
![image](https://user-images.githubusercontent.com/51117782/83612704-ac16f400-a57a-11ea-89e3-3f4e17e95dda.png)

Repo file: https://devforum.roblox.com/uploads/short-url/pn1v2zXgk3e5QxwU62m2QjnocD4.rbxl

**Comment by DanzLua** [comment]
Another example of this happening.

https://cdn.discordapp.com/attachments/644398962614206464/723750864120184892/zonerepo.rbxl
